export enum ACTION_GET{
    SHOW_MENU = 'SHOW_MENU',
    REMOVE_CART = 'REMOVE_CART',
    SHOW_PRODUCTDETAIL ='SHOW_PRODUCTDETAIL',
    SHOW_CART= 'SHOW_CART',
    ADD_CART= 'ADD_CART',
    DELETE_CART = 'DELETE_CART',
    GET_DETAIL_USER = 'GET_DETAIL_USER',
    DISPLAY_MENU_ACCOUNT = 'DISPLAY_MENU_ACCOUNT',
}


